UI test
kea-semester-1/Semester-Project pull request #67
Opened 2023-12-22 10:39 UTC by Erol0019

Lavet cypress og tilføjet i HTML

2023-12-26 15:27 UTC, Moshizzl3 commented
Very nice :)

2023-12-26 15:31 UTC, Moshizzl3 requested changes

2023-12-26 15:31 UTC, Moshizzl3 commented on cypress/e2e/TestingErrors/character.cy.js
> +    // Forsøger at oprette karakter uden et navn
We are using English in the rest of the project, could we change it here so it's consistent?

2023-12-26 15:31 UTC, Moshizzl3 commented on .nuxt/nuxt.json
> +    "rootDir": "C:/Users/erol-/OneDrive - Zealand/Skrivebord/SemesterTesting/Semester-Project"
what us this? would it work for the rest of us?

2023-12-27 22:05 UTC, martinlaursen97 commented on client/cypress/e2e/TestingErrors/world.cy.js
> +  cy.contains(`Name: Orc`).should('be.visible')
testen vil fejle hvis en character med navnet "Orc" ikke findes, eller hvis der er flere end 1 character, siden der vil være flere div's med `data-test="enterWorld"`

2023-12-27 22:05 UTC, martinlaursen97 commented on rpg_api/tests/pytest/endpoint/test_post_places.py
> +    assert response_data["radius"] == 75
Du kan slette det her fra branchen, siden det allerede er i https://github.com/kea-semester-1/Semester-Project/pull/81

2023-12-27 22:06 UTC, martinlaursen97 commented on client/cypress/e2e/TestingErrors/world.cy.js
> +  cy.wait(2000)
```suggestion
 cy.login('user0@example.com', 'password');
```

2023-12-27 22:07 UTC, martinlaursen97 commented on client/cypress/e2e/spec.cy.js
> +    cy.wait(loginWaitTime)
```suggestion
    cy.login('user0@example.com', 'password');
```

2023-12-28 16:05 UTC, Erol0019 commented on client/cypress/e2e/spec.cy.js
> +    cy.wait(loginWaitTime)
fixed

2023-12-28 16:05 UTC, Erol0019 commented on client/cypress/e2e/TestingErrors/world.cy.js
> +  cy.wait(2000)
fixed

2023-12-28 16:07 UTC, Erol0019 commented on rpg_api/tests/pytest/endpoint/test_post_places.py
> +    assert response_data["radius"] == 75
er slettet

2023-12-28 16:08 UTC, Erol0019 commented on client/cypress/e2e/TestingErrors/world.cy.js
> +  cy.contains(`Name: Orc`).should('be.visible')
resolved

2023-12-28 16:27 UTC, Erol0019 commented on .nuxt/nuxt.json
> +    "rootDir": "C:/Users/erol-/OneDrive - Zealand/Skrivebord/SemesterTesting/Semester-Project"
resolved

2023-12-28 16:37 UTC, martinlaursen97 approved these changes

2023-12-28 16:43 UTC, Moshizzl3 approved these changes

2023-12-28 16:43 UTC, merged