Tests for various endpoints
kea-semester-1/Semester-Project pull request #70
Opened 2023-12-25 05:53 UTC by Amiiiiiiiin

Developed tests for the following endpoints (#51):
* `GET /base-classes`
* `GET /characters`
* `GET /characters/place/{character_id}`
* `POST /characters`
* `PATCH /character-locations/{character_id}`

One test is missing, which has had an issue created here: https://github.com/kea-semester-1/Semester-Project/issues/69

2023-12-25 12:37 UTC, Moshizzl3 commented
Very nice! :)

2023-12-25 13:28 UTC, Moshizzl3 requested changes

2023-12-25 13:49 UTC, martinlaursen97 requested changes
Nice

2023-12-25 13:49 UTC, martinlaursen97 commented on rpg_api/tests/pytest/endpoint/character_location/test_patch_character_locations.py
> +)
I think we should store the max size of int32 in constants.py
```python
INT32_SIZE = 2**31 - 1
```

That way it will be easier to see what the test is doing, and to explain at the exam:

```suggestion
@pytest.mark.parametrize(
    "x, y",
    [
        # Int32 boundaries
        (-constants.INT32_SIZE + 1, 0),
        constants.INT32_SIZE, 0),
		...
    ],
)
```

2023-12-25 13:49 UTC, martinlaursen97 commented on rpg_api/tests/pytest/endpoint/base_classes/test_get_base_classes.py
> +    assert len(response.json()["data"]) == 0
use `get_data` from test_utils to make the tests cleaner

```suggestion
@pytest.mark.anyio
async def test_get_base_classes_empty_list(client: AsyncClient) -> None:
    """Test get all base classes with 0 base classes in the database: 200."""

    response = await client.get(url)
    assert response.status_code == status.HTTP_200_OK
    
    response_data = get_data(response)
    assert response_data  == []
```

2023-12-26 18:52 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/base_classes/test_get_base_classes.py
> +def get_user_header(token: str) -> dict[str, Any]:
Removed, as it was not used.

2023-12-26 18:52 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/character_location/test_patch_character_locations.py
> +
Have converted all the tests to utilize this.

2023-12-26 18:53 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/character_location/test_patch_character_locations.py
> +async def test_patch_character_location_missing_data(client: AsyncClient) -> None:
Changed the name of the test.

2023-12-26 18:53 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/character_location/test_patch_character_locations.py
> +async def test_patch_character_location_invalid_float(client: AsyncClient) -> None:
Deleted the test as I utilised the parameterized functionality instead.

2023-12-26 18:54 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters_place.py
> +async def test_get_character_place_named_place_outside_radius_boundary(
Converted this and several other tests to use parameterized

2023-12-26 18:54 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/characters/test_post_characters.py
> +    baseClass = await factories.BaseClassFactory.create()
Updated this name and numerous others to use snake case instead of camel case

2023-12-26 18:55 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/characters/test_post_characters.py
> +    charData = {
Updated this name and numerous others to use snake case instead of camel case

2023-12-26 18:56 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/character_location/test_patch_character_locations.py
> +)
I did this, but I explicitly stated the values in the constants file:
INT32_MAX: int = 2147483647
INT32_MIN: int = -2147483648

2023-12-26 18:56 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/base_classes/test_get_base_classes.py
> +    assert len(response.json()["data"]) == 0
Utilised it on the tests where it was relevant

2023-12-26 18:57 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters_place.py
> +    await client.patch(f"{updateUrl}/{character.id}", headers=header, json=charLocation)
Changed this test and others where relevant to use DAO, I wasn't happy with using another endpoint in a test, but wasn't sure on how else to do it at the time.

2023-12-26 19:51 UTC, martinlaursen97 requested changes
Perhaps we don't need to check for invalid HTTP methods in every endpoint, but maybe a test should be written for `api/monitoring/health` that does this

2023-12-26 19:51 UTC, martinlaursen97 commented on rpg_api/tests/pytest/endpoint/base_classes/test_get_base_classes.py
> +    assert response.status_code == status.HTTP_405_METHOD_NOT_ALLOWED
```suggestion
@pytest.mark.anyio
async def test_base_classes_method_not_allowed_post(client: AsyncClient) -> None:
    """Test that POST method is not allowed for the base-classes endpoint: 405."""

    response = await client.post(url, json={"name": "NewClass"})

    assert response.status_code == status.HTTP_405_METHOD_NOT_ALLOWED


@pytest.mark.anyio
async def test_base_classes_method_not_allowed_put(client: AsyncClient) -> None:
    """Test that PUT method is not allowed for the base-classes endpoint: 405."""

    response = await client.put(url, json={"name": "UpdatedClass"})

    assert response.status_code == status.HTTP_405_METHOD_NOT_ALLOWED


@pytest.mark.anyio
async def test_base_classes_method_not_allowed_delete(client: AsyncClient) -> None:
    """Test that DELETE method is not allowed for the base-classes endpoint: 405."""

    response = await client.delete(url)

    assert response.status_code == status.HTTP_405_METHOD_NOT_ALLOWED


@pytest.mark.anyio
async def test_base_classes_method_not_allowed_patch(client: AsyncClient) -> None:
    """Test that PATCH method is not allowed for the base-classes endpoint: 405."""

    response = await client.patch(url, json={"name": "PatchedClass"})

    assert response.status_code == status.HTTP_405_METHOD_NOT_ALLOWED


@pytest.mark.anyio
async def test_base_classes_method_not_allowed_options(client: AsyncClient) -> None:
    """Test that OPTIONS method is not allowed for the base-classes endpoint: 405."""

    response = await client.options(url)

    assert response.status_code == status.HTTP_405_METHOD_NOT_ALLOWED


@pytest.mark.anyio
async def test_base_classes_method_not_allowed_head(client: AsyncClient) -> None:
    """Test that HEAD method is not allowed for the base-classes endpoint: 405."""

    response = await client.head(url)

    assert response.status_code == status.HTTP_405_METHOD_NOT_ALLOWED
```

You can probably do this in a single parameterized test.
Does this work?

```python
@pytest.mark.anyio
@pytest.mark.parametrize(
    "method, params",
    [
        ("put", {"json": {"name": "UpdatedClass"}}),
        ("delete", {}),
        ("patch", {"json": {"name": "PatchedClass"}}),
        ("options", {}),
        ("head", {})
    ],
)
async def test_base_classes_method_not_allowed(client: AsyncClient, method: str, params: dict) -> None:
    """Test that various HTTP methods are not allowed for the base-classes endpoint: 405."""

    http_method = getattr(client, method)
    response = await http_method(url, **params)

    assert response.status_code == status.HTTP_405_METHOD_NOT_ALLOWED
```

2023-12-26 19:51 UTC, martinlaursen97 commented on rpg_api/tests/pytest/endpoint/character_location/test_patch_character_locations.py
> +        (0, 2147483646),
Use the INT32 constants

2023-12-26 19:51 UTC, martinlaursen97 commented on rpg_api/tests/pytest/endpoint/character_location/test_patch_character_locations.py
> +    invalidId = uuid.uuid4()
```suggestion
    invalid_id = uuid.uuid4()
```

2023-12-26 19:51 UTC, martinlaursen97 commented on rpg_api/tests/pytest/endpoint/character_location/test_patch_character_locations.py
> +    assert response.status_code == status.HTTP_405_METHOD_NOT_ALLOWED
Same as mentioned before

2023-12-26 19:51 UTC, martinlaursen97 commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters.py
> +    assert len(response_data) == 2
```suggestion
@pytest.mark.anyio
async def test_get_characters(client: AsyncClient) -> None:
    """Test get all characters: 200."""

    user = await factories.BaseUserFactory.create()
    header = test_utils.get_user_header(user.id)

    characters = [
        await factories.CharacterFactory.create(user=user),
        await factories.CharacterFactory.create(user=user)
    ]
    
    # Character not owned by current user
    await factories.CharacterFactory.create() 

    # Ensure character_location and base_class are not None for mypy
    for character in characters:
        assert character.character_location is not None
        assert character.base_class is not None

    response = await client.get(url, headers=header)
    assert response.status_code == status.HTTP_200_OK

    response_data = test_utils.get_data(response)
    
    for index, character in enumerate(characters):
        assert response_data[index]["id"] == str(character.id)
        assert response_data[index]["gender"] == character.gender
        assert response_data[index]["character_name"] == character.character_name
        assert response_data[index]["alive"] == character.alive
        assert response_data[index]["level"] == character.level
        assert response_data[index]["xp"] == character.xp
        assert response_data[index]["money"] == character.money
        assert response_data[index]["base_class"].get("name") == character.base_class.name
        assert response_data[index]["character_location"]["x"] == character.character_location.x
        assert response_data[index]["character_location"]["y"] == character.character_location.y

    assert len(response_data) == 2
```

I don't think test with an empty db / 1 characters are needed, and we can just stick with this one, since it is testing the same logic as the others anyways

2023-12-26 19:51 UTC, martinlaursen97 commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters.py
> +    response = await client.put(url, json={"name": "Character"})
same as mentioned before

2023-12-26 19:51 UTC, martinlaursen97 commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters_place.py
> +
I think some tests in this file can be replaced with this, since it is covering the same, and is also doing boundary stuff

```python
def _url(character_id: UUID) -> str:
    return f"/api/postgres/characters/place/{character_id}"


DEFAULT_PLACE_NAME = "Goldshire"
DEFAULT_CHARACTER_X = 10


@pytest.mark.anyio
@pytest.mark.parametrize(
    "place_radius, expected_place_name",
    [
        (10.00, DEFAULT_PLACE_NAME),
        (10.01, DEFAULT_PLACE_NAME),
        (09.99, "Wilderness"),
        (09.98, "Wilderness"),
    ],
)
async def test_get_character_place_name(
    client: AsyncClient,
    place_radius: float,
    expected_place_name: str,
    daos: AllDAOs,
) -> None:
    """Test get character place name: 200."""

    user = await factories.BaseUserFactory.create()
    await factories.PlaceFactory.create(
        radius=place_radius,
        name=DEFAULT_PLACE_NAME,
        x=0,
        y=0,
    )

    character = await factories.CharacterFactory.create(
        user=user,
    )

    # TODO: remove this when character factory is fixed
    await daos.character_location.update(
        character.character_location.id,  # type: ignore
        dtos.CharacterLocationUpdateDTO(x=DEFAULT_CHARACTER_X, y=0),
    )

    header = get_user_header(user.id)

    response = await client.get(_url(character.id), headers=header)
    assert response.status_code == status.HTTP_200_OK

    response_data = get_data(response)
    assert response_data["name"] == expected_place_name
```

2023-12-26 19:51 UTC, martinlaursen97 commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters_place.py
> +    invalidId = uuid.uuid4()
```suggestion
    invalid_id = uuid.uuid4()
```

2023-12-26 19:51 UTC, martinlaursen97 commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters_place.py
> +    assert response.status_code == status.HTTP_405_METHOD_NOT_ALLOWED
same as mentioned before

2023-12-26 20:50 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters.py
> +    assert len(response_data) == 2
I think it's nice to have tests that cover for different states that the database could be in (i.e empty, single entry and multiple entries), with the only downside being a minor impact on test runtime.

@Moshizzl3 @Erol0019 Thoughts

2023-12-26 21:16 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters_place.py
> +    invalidId = uuid.uuid4()
Fixed

2023-12-26 21:17 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/character_location/test_patch_character_locations.py
> +        (0, 2147483646),
fixed to use constant-1 and +1

2023-12-26 21:18 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/base_classes/test_get_base_classes.py
> +    assert response.status_code == status.HTTP_405_METHOD_NOT_ALLOWED
I've edited all the HTTP method tests to use this format for each disallowed method, marked the other comments regarding this as resolved.

2023-12-26 21:22 UTC, Amiiiiiiiin commented
> Perhaps we don't need to check for invalid HTTP methods in every endpoint, but maybe a test should be written for `api/monitoring/health` that does this

I think it's fine to do for now, but we can look at it later perhaps if we're worried about duplication.

2023-12-26 21:41 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters_place.py
> +
My thought process behind creating different tests is primarily that each test gets to have one focus for each different scenario. I believe doing it this way allows us to test each focuspoint with varying types of parameters such as negative numbers,  positive numbers, 0, small numbers, large numbers, boundaries etc.

`test_get_character_place_named_place` is focused on scenarios where a character is on the exact coordinates of a place
`test_get_character_place_named_place_radius_inside_boundary` is focused scenarios where on a character is in the radius of a place, but not on the exact coordinates
`test_get_character_place_named_place_outside_radius_boundary` is focused on testing the boundaries of a place's radius

With the change from the coordinates being int to floats, I believe we actually introduced a need for more tests (In terms of more parameters) since floats have like 6 decimals.

2023-12-26 22:58 UTC, martinlaursen97 commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters_place.py
> +
For exam purposes we need to do boundary value analysis whenever possible though, and this would be the perfect test for that imo.
As the tests are written now, they are not really doing it

2023-12-26 23:00 UTC, martinlaursen97 commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters.py
> +    assert len(response_data) == 2
That's fair, but you should use a loop when possible to increase readability, and also create characters that are not owned by the current user, since they are not supposed to be found in this endpoint

2023-12-26 23:03 UTC, martinlaursen97 commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters.py
> +    assert len(response_data) == 2
You could even create a function at the top of the file that does the asserts, since it is a lot of duplicate code

```python
def _assert_character_data(expected_character: Character, actual_data: dict[str, Any]) -> None:
    """Asserts that the actual data from the response matches the expected character data."""
    assert actual_data["id"] == str(expected_character.id)
    assert actual_data["gender"] == expected_character.gender
    assert actual_data["character_name"] == expected_character.character_name
    assert actual_data["alive"] == expected_character.alive
    assert actual_data["level"] == expected_character.level
    assert actual_data["xp"] == expected_character.xp
    assert actual_data["money"] == expected_character.money
    assert actual_data["base_class"]["name"] == expected_character.base_class.name
    assert actual_data["character_location"]["x"] == expected_character.character_location.x
    assert actual_data["character_location"]["y"] == expected_character.character_location.y

```

then use it like this:
```python
for index, character in enumerate(characters):
	_assert_character_data(character, response_data[index])
```

2023-12-26 23:57 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters.py
> +    assert len(response_data) == 2
I've updated the test to reflect your feedback. I'll let you mark this comment as resolved in case there's anything you want to follow up on in regards to the changes made.

2023-12-27 00:11 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters_place.py
> +
All the parameters used for `test_get_character_place_named_place_radius_inside_boundary` & `test_get_character_place_named_place_outside_radius_boundary` should be the exact boundaries for the different radiuses set in different scenarios, though as if they were ints and not floats. 

We can implement your suggestion, however I am worried that we just won't get to enough scenarios as we're only updating one coordinate. That's why I made it into two different tests, where one is focused on the boundary inside the radius and one outside. Let me know what you think tomorrow 😁

2023-12-27 13:42 UTC, Moshizzl3 commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters_place.py
> +
I think we should have specific tests aswell that clear tests the boundary, can't we just have both?

2023-12-27 13:44 UTC, martinlaursen97 commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters_place.py
> +
I think you can keep the tests there, but also include the suggestion so we are doing boundary value analysis

2023-12-27 16:24 UTC, Amiiiiiiiin commented on rpg_api/tests/pytest/endpoint/characters/test_get_characters_place.py
> +
I've updated the parameters to account for the change from int to float as well as adjusted the parameters from your feedback. I'll let you mark this conversation as resolved in case you have any follow up feedback

2023-12-27 17:02 UTC, martinlaursen97 approved these changes

2023-12-27 19:42 UTC, Moshizzl3 approved these changes

2023-12-27 20:00 UTC, merged